source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Chimehack-Mobile' do
    pod 'SnapKit', '~> 3.2.0'
    pod 'RealmSwift'
    pod 'Alamofire', '~> 4.4'
    pod 'pop', '~> 1.0'
end

